### ISSUE TITLE
Position page options in the WP menu

### ISSUE THREAD

**Issue by K15Lmk98** [taunoha/cmb-theme-options-tabs#2]
This is an automatic translation

Hello,
I saw that you can rename the title page of the options in the WP menu with the filter "cmb2_theme_options_tabs_page_title".

Can you move the options page link out of the Wp SETTINGS menu and apply an icon to it?

Thank you, Claudio_

**Comment by taunoha** [comment]
Currently there is no other option than removing 'parent_slug' option form code.
For futher information you should take a look at CMB2 Box properties documentation: https://github.com/CMB2/CMB2/wiki/Box-Properties

**Comment by K15Lmk98** [comment]
Thank you, Claudio_
