### ISSUE TITLE
Compatibility with Php 7.2+

### ISSUE THREAD

**Issue by K15Lmk98** [taunoha/cmb-theme-options-tabs#3]
This is an automatic translation.

Hello,
the plugin is not compatible with Php 7.2+

An update would be appreciated, thanks.

Claudio_

**Comment by taunoha** [comment]
Please take a look at the new release.
I have tested it with PHP 7.3.3.

Please let me know if there are still issues with PHP7+.

**Comment by K15Lmk98** [comment]
This is an automatic translation.

Hi Taunoha,
I'm doing some checks with Php 7.2.20 - Local MAMP OsX installation -
I have anomalies. Sometimes from error.

I keep you informed as soon as I understand the problem.

Thanks, Claudio_
